// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go
//
// Generated by this command:
//
//	mockgen -source=repository.go -destination=mock/mock_repository.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	model "github.com/shibayama-club/keyhub/internal/domain/model"
	repository "github.com/shibayama-club/keyhub/internal/domain/repository"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// ConsumeOAuthState mocks base method.
func (m *MockRepository) ConsumeOAuthState(ctx context.Context, state string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConsumeOAuthState", ctx, state)
	ret0, _ := ret[0].(error)
	return ret0
}

// ConsumeOAuthState indicates an expected call of ConsumeOAuthState.
func (mr *MockRepositoryMockRecorder) ConsumeOAuthState(ctx, state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConsumeOAuthState", reflect.TypeOf((*MockRepository)(nil).ConsumeOAuthState), ctx, state)
}

// CreateAppSession mocks base method.
func (m *MockRepository) CreateAppSession(ctx context.Context, arg repository.CreateAppSessionArg) (model.AppSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAppSession", ctx, arg)
	ret0, _ := ret[0].(model.AppSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAppSession indicates an expected call of CreateAppSession.
func (mr *MockRepositoryMockRecorder) CreateAppSession(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAppSession", reflect.TypeOf((*MockRepository)(nil).CreateAppSession), ctx, arg)
}

// CreateSession mocks base method.
func (m *MockRepository) CreateSession(ctx context.Context, arg repository.CreateConsoleSessionArg) (model.ConsoleSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSession", ctx, arg)
	ret0, _ := ret[0].(model.ConsoleSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSession indicates an expected call of CreateSession.
func (mr *MockRepositoryMockRecorder) CreateSession(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSession", reflect.TypeOf((*MockRepository)(nil).CreateSession), ctx, arg)
}

// CreateTenant mocks base method.
func (m *MockRepository) CreateTenant(ctx context.Context, arg repository.CreateTenantArg) (model.Tenant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTenant", ctx, arg)
	ret0, _ := ret[0].(model.Tenant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTenant indicates an expected call of CreateTenant.
func (mr *MockRepositoryMockRecorder) CreateTenant(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTenant", reflect.TypeOf((*MockRepository)(nil).CreateTenant), ctx, arg)
}

// CreateTenantJoinCode mocks base method.
func (m *MockRepository) CreateTenantJoinCode(ctx context.Context, arg repository.CreateTenantJoinCodeArg) (model.TenantJoinCodeEntity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTenantJoinCode", ctx, arg)
	ret0, _ := ret[0].(model.TenantJoinCodeEntity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTenantJoinCode indicates an expected call of CreateTenantJoinCode.
func (mr *MockRepositoryMockRecorder) CreateTenantJoinCode(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTenantJoinCode", reflect.TypeOf((*MockRepository)(nil).CreateTenantJoinCode), ctx, arg)
}

// CreateTenantMembership mocks base method.
func (m *MockRepository) CreateTenantMembership(ctx context.Context, membership model.TenantMembership) (model.TenantMembership, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTenantMembership", ctx, membership)
	ret0, _ := ret[0].(model.TenantMembership)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTenantMembership indicates an expected call of CreateTenantMembership.
func (mr *MockRepositoryMockRecorder) CreateTenantMembership(ctx, membership any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTenantMembership", reflect.TypeOf((*MockRepository)(nil).CreateTenantMembership), ctx, membership)
}

// DeleteSession mocks base method.
func (m *MockRepository) DeleteSession(ctx context.Context, sessionID model.ConsoleSessionID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSession", ctx, sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSession indicates an expected call of DeleteSession.
func (mr *MockRepositoryMockRecorder) DeleteSession(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSession", reflect.TypeOf((*MockRepository)(nil).DeleteSession), ctx, sessionID)
}

// GetAllTenants mocks base method.
func (m *MockRepository) GetAllTenants(ctx context.Context, organizationID model.OrganizationID) ([]model.Tenant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllTenants", ctx, organizationID)
	ret0, _ := ret[0].([]model.Tenant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllTenants indicates an expected call of GetAllTenants.
func (mr *MockRepositoryMockRecorder) GetAllTenants(ctx, organizationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllTenants", reflect.TypeOf((*MockRepository)(nil).GetAllTenants), ctx, organizationID)
}

// GetAppSession mocks base method.
func (m *MockRepository) GetAppSession(ctx context.Context, sessionID model.AppSessionID) (model.AppSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAppSession", ctx, sessionID)
	ret0, _ := ret[0].(model.AppSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAppSession indicates an expected call of GetAppSession.
func (mr *MockRepositoryMockRecorder) GetAppSession(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAppSession", reflect.TypeOf((*MockRepository)(nil).GetAppSession), ctx, sessionID)
}

// GetOAuthState mocks base method.
func (m *MockRepository) GetOAuthState(ctx context.Context, state string) (model.OAuthState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOAuthState", ctx, state)
	ret0, _ := ret[0].(model.OAuthState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOAuthState indicates an expected call of GetOAuthState.
func (mr *MockRepositoryMockRecorder) GetOAuthState(ctx, state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOAuthState", reflect.TypeOf((*MockRepository)(nil).GetOAuthState), ctx, state)
}

// GetSession mocks base method.
func (m *MockRepository) GetSession(ctx context.Context, sessionID model.ConsoleSessionID) (model.ConsoleSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSession", ctx, sessionID)
	ret0, _ := ret[0].(model.ConsoleSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSession indicates an expected call of GetSession.
func (mr *MockRepositoryMockRecorder) GetSession(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSession", reflect.TypeOf((*MockRepository)(nil).GetSession), ctx, sessionID)
}

// GetTenantByID mocks base method.
func (m *MockRepository) GetTenantByID(ctx context.Context, id model.TenantID) (repository.TenantWithJoinCode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTenantByID", ctx, id)
	ret0, _ := ret[0].(repository.TenantWithJoinCode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTenantByID indicates an expected call of GetTenantByID.
func (mr *MockRepositoryMockRecorder) GetTenantByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTenantByID", reflect.TypeOf((*MockRepository)(nil).GetTenantByID), ctx, id)
}

// GetTenantByJoinCode mocks base method.
func (m *MockRepository) GetTenantByJoinCode(ctx context.Context, code model.TenantJoinCode) (model.Tenant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTenantByJoinCode", ctx, code)
	ret0, _ := ret[0].(model.Tenant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTenantByJoinCode indicates an expected call of GetTenantByJoinCode.
func (mr *MockRepositoryMockRecorder) GetTenantByJoinCode(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTenantByJoinCode", reflect.TypeOf((*MockRepository)(nil).GetTenantByJoinCode), ctx, code)
}

// GetTenantMembershipByTenantAndUser mocks base method.
func (m *MockRepository) GetTenantMembershipByTenantAndUser(ctx context.Context, tenantID model.TenantID, userID model.UserID) (model.TenantMembership, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTenantMembershipByTenantAndUser", ctx, tenantID, userID)
	ret0, _ := ret[0].(model.TenantMembership)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTenantMembershipByTenantAndUser indicates an expected call of GetTenantMembershipByTenantAndUser.
func (mr *MockRepositoryMockRecorder) GetTenantMembershipByTenantAndUser(ctx, tenantID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTenantMembershipByTenantAndUser", reflect.TypeOf((*MockRepository)(nil).GetTenantMembershipByTenantAndUser), ctx, tenantID, userID)
}

// GetTenantsByUserID mocks base method.
func (m *MockRepository) GetTenantsByUserID(ctx context.Context, userID model.UserID) ([]repository.TenantWithMemberCount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTenantsByUserID", ctx, userID)
	ret0, _ := ret[0].([]repository.TenantWithMemberCount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTenantsByUserID indicates an expected call of GetTenantsByUserID.
func (mr *MockRepositoryMockRecorder) GetTenantsByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTenantsByUserID", reflect.TypeOf((*MockRepository)(nil).GetTenantsByUserID), ctx, userID)
}

// GetUser mocks base method.
func (m *MockRepository) GetUser(ctx context.Context, userID model.UserID) (model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", ctx, userID)
	ret0, _ := ret[0].(model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockRepositoryMockRecorder) GetUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockRepository)(nil).GetUser), ctx, userID)
}

// GetUserByProviderIdentity mocks base method.
func (m *MockRepository) GetUserByProviderIdentity(ctx context.Context, provider, providerSub string) (model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByProviderIdentity", ctx, provider, providerSub)
	ret0, _ := ret[0].(model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByProviderIdentity indicates an expected call of GetUserByProviderIdentity.
func (mr *MockRepositoryMockRecorder) GetUserByProviderIdentity(ctx, provider, providerSub any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByProviderIdentity", reflect.TypeOf((*MockRepository)(nil).GetUserByProviderIdentity), ctx, provider, providerSub)
}

// IncrementJoinCodeUsedCount mocks base method.
func (m *MockRepository) IncrementJoinCodeUsedCount(ctx context.Context, code model.TenantJoinCode) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementJoinCodeUsedCount", ctx, code)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrementJoinCodeUsedCount indicates an expected call of IncrementJoinCodeUsedCount.
func (mr *MockRepositoryMockRecorder) IncrementJoinCodeUsedCount(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementJoinCodeUsedCount", reflect.TypeOf((*MockRepository)(nil).IncrementJoinCodeUsedCount), ctx, code)
}

// RevokeAppSession mocks base method.
func (m *MockRepository) RevokeAppSession(ctx context.Context, sessionID model.AppSessionID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeAppSession", ctx, sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeAppSession indicates an expected call of RevokeAppSession.
func (mr *MockRepositoryMockRecorder) RevokeAppSession(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeAppSession", reflect.TypeOf((*MockRepository)(nil).RevokeAppSession), ctx, sessionID)
}

// SaveOAuthState mocks base method.
func (m *MockRepository) SaveOAuthState(ctx context.Context, oauthState model.OAuthState) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveOAuthState", ctx, oauthState)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveOAuthState indicates an expected call of SaveOAuthState.
func (mr *MockRepositoryMockRecorder) SaveOAuthState(ctx, oauthState any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveOAuthState", reflect.TypeOf((*MockRepository)(nil).SaveOAuthState), ctx, oauthState)
}

// UpdateTenant mocks base method.
func (m *MockRepository) UpdateTenant(ctx context.Context, arg repository.UpdateTenantArg) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTenant", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTenant indicates an expected call of UpdateTenant.
func (mr *MockRepositoryMockRecorder) UpdateTenant(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTenant", reflect.TypeOf((*MockRepository)(nil).UpdateTenant), ctx, arg)
}

// UpdateTenantJoinCodeByTenantId mocks base method.
func (m *MockRepository) UpdateTenantJoinCodeByTenantId(ctx context.Context, arg repository.UpdateTenantJoinCodeArg) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTenantJoinCodeByTenantId", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTenantJoinCodeByTenantId indicates an expected call of UpdateTenantJoinCodeByTenantId.
func (mr *MockRepositoryMockRecorder) UpdateTenantJoinCodeByTenantId(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTenantJoinCodeByTenantId", reflect.TypeOf((*MockRepository)(nil).UpdateTenantJoinCodeByTenantId), ctx, arg)
}

// UpsertUser mocks base method.
func (m *MockRepository) UpsertUser(ctx context.Context, arg repository.UpsertUserArg) (model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertUser", ctx, arg)
	ret0, _ := ret[0].(model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertUser indicates an expected call of UpsertUser.
func (mr *MockRepositoryMockRecorder) UpsertUser(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertUser", reflect.TypeOf((*MockRepository)(nil).UpsertUser), ctx, arg)
}

// UpsertUserIdentity mocks base method.
func (m *MockRepository) UpsertUserIdentity(ctx context.Context, arg repository.UpsertUserIdentityArg) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertUserIdentity", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertUserIdentity indicates an expected call of UpsertUserIdentity.
func (mr *MockRepositoryMockRecorder) UpsertUserIdentity(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertUserIdentity", reflect.TypeOf((*MockRepository)(nil).UpsertUserIdentity), ctx, arg)
}

// WithTransaction mocks base method.
func (m *MockRepository) WithTransaction(ctx context.Context, fn func(context.Context, repository.Transaction) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTransaction", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithTransaction indicates an expected call of WithTransaction.
func (mr *MockRepositoryMockRecorder) WithTransaction(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTransaction", reflect.TypeOf((*MockRepository)(nil).WithTransaction), ctx, fn)
}

// MockTransaction is a mock of Transaction interface.
type MockTransaction struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionMockRecorder
	isgomock struct{}
}

// MockTransactionMockRecorder is the mock recorder for MockTransaction.
type MockTransactionMockRecorder struct {
	mock *MockTransaction
}

// NewMockTransaction creates a new mock instance.
func NewMockTransaction(ctrl *gomock.Controller) *MockTransaction {
	mock := &MockTransaction{ctrl: ctrl}
	mock.recorder = &MockTransactionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransaction) EXPECT() *MockTransactionMockRecorder {
	return m.recorder
}

// ConsumeOAuthState mocks base method.
func (m *MockTransaction) ConsumeOAuthState(ctx context.Context, state string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConsumeOAuthState", ctx, state)
	ret0, _ := ret[0].(error)
	return ret0
}

// ConsumeOAuthState indicates an expected call of ConsumeOAuthState.
func (mr *MockTransactionMockRecorder) ConsumeOAuthState(ctx, state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConsumeOAuthState", reflect.TypeOf((*MockTransaction)(nil).ConsumeOAuthState), ctx, state)
}

// CreateAppSession mocks base method.
func (m *MockTransaction) CreateAppSession(ctx context.Context, arg repository.CreateAppSessionArg) (model.AppSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAppSession", ctx, arg)
	ret0, _ := ret[0].(model.AppSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAppSession indicates an expected call of CreateAppSession.
func (mr *MockTransactionMockRecorder) CreateAppSession(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAppSession", reflect.TypeOf((*MockTransaction)(nil).CreateAppSession), ctx, arg)
}

// CreateSession mocks base method.
func (m *MockTransaction) CreateSession(ctx context.Context, arg repository.CreateConsoleSessionArg) (model.ConsoleSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSession", ctx, arg)
	ret0, _ := ret[0].(model.ConsoleSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSession indicates an expected call of CreateSession.
func (mr *MockTransactionMockRecorder) CreateSession(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSession", reflect.TypeOf((*MockTransaction)(nil).CreateSession), ctx, arg)
}

// CreateTenant mocks base method.
func (m *MockTransaction) CreateTenant(ctx context.Context, arg repository.CreateTenantArg) (model.Tenant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTenant", ctx, arg)
	ret0, _ := ret[0].(model.Tenant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTenant indicates an expected call of CreateTenant.
func (mr *MockTransactionMockRecorder) CreateTenant(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTenant", reflect.TypeOf((*MockTransaction)(nil).CreateTenant), ctx, arg)
}

// CreateTenantJoinCode mocks base method.
func (m *MockTransaction) CreateTenantJoinCode(ctx context.Context, arg repository.CreateTenantJoinCodeArg) (model.TenantJoinCodeEntity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTenantJoinCode", ctx, arg)
	ret0, _ := ret[0].(model.TenantJoinCodeEntity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTenantJoinCode indicates an expected call of CreateTenantJoinCode.
func (mr *MockTransactionMockRecorder) CreateTenantJoinCode(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTenantJoinCode", reflect.TypeOf((*MockTransaction)(nil).CreateTenantJoinCode), ctx, arg)
}

// CreateTenantMembership mocks base method.
func (m *MockTransaction) CreateTenantMembership(ctx context.Context, membership model.TenantMembership) (model.TenantMembership, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTenantMembership", ctx, membership)
	ret0, _ := ret[0].(model.TenantMembership)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTenantMembership indicates an expected call of CreateTenantMembership.
func (mr *MockTransactionMockRecorder) CreateTenantMembership(ctx, membership any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTenantMembership", reflect.TypeOf((*MockTransaction)(nil).CreateTenantMembership), ctx, membership)
}

// DeleteSession mocks base method.
func (m *MockTransaction) DeleteSession(ctx context.Context, sessionID model.ConsoleSessionID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSession", ctx, sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSession indicates an expected call of DeleteSession.
func (mr *MockTransactionMockRecorder) DeleteSession(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSession", reflect.TypeOf((*MockTransaction)(nil).DeleteSession), ctx, sessionID)
}

// GetAllTenants mocks base method.
func (m *MockTransaction) GetAllTenants(ctx context.Context, organizationID model.OrganizationID) ([]model.Tenant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllTenants", ctx, organizationID)
	ret0, _ := ret[0].([]model.Tenant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllTenants indicates an expected call of GetAllTenants.
func (mr *MockTransactionMockRecorder) GetAllTenants(ctx, organizationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllTenants", reflect.TypeOf((*MockTransaction)(nil).GetAllTenants), ctx, organizationID)
}

// GetAppSession mocks base method.
func (m *MockTransaction) GetAppSession(ctx context.Context, sessionID model.AppSessionID) (model.AppSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAppSession", ctx, sessionID)
	ret0, _ := ret[0].(model.AppSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAppSession indicates an expected call of GetAppSession.
func (mr *MockTransactionMockRecorder) GetAppSession(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAppSession", reflect.TypeOf((*MockTransaction)(nil).GetAppSession), ctx, sessionID)
}

// GetOAuthState mocks base method.
func (m *MockTransaction) GetOAuthState(ctx context.Context, state string) (model.OAuthState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOAuthState", ctx, state)
	ret0, _ := ret[0].(model.OAuthState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOAuthState indicates an expected call of GetOAuthState.
func (mr *MockTransactionMockRecorder) GetOAuthState(ctx, state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOAuthState", reflect.TypeOf((*MockTransaction)(nil).GetOAuthState), ctx, state)
}

// GetSession mocks base method.
func (m *MockTransaction) GetSession(ctx context.Context, sessionID model.ConsoleSessionID) (model.ConsoleSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSession", ctx, sessionID)
	ret0, _ := ret[0].(model.ConsoleSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSession indicates an expected call of GetSession.
func (mr *MockTransactionMockRecorder) GetSession(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSession", reflect.TypeOf((*MockTransaction)(nil).GetSession), ctx, sessionID)
}

// GetTenantByID mocks base method.
func (m *MockTransaction) GetTenantByID(ctx context.Context, id model.TenantID) (repository.TenantWithJoinCode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTenantByID", ctx, id)
	ret0, _ := ret[0].(repository.TenantWithJoinCode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTenantByID indicates an expected call of GetTenantByID.
func (mr *MockTransactionMockRecorder) GetTenantByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTenantByID", reflect.TypeOf((*MockTransaction)(nil).GetTenantByID), ctx, id)
}

// GetTenantByJoinCode mocks base method.
func (m *MockTransaction) GetTenantByJoinCode(ctx context.Context, code model.TenantJoinCode) (model.Tenant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTenantByJoinCode", ctx, code)
	ret0, _ := ret[0].(model.Tenant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTenantByJoinCode indicates an expected call of GetTenantByJoinCode.
func (mr *MockTransactionMockRecorder) GetTenantByJoinCode(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTenantByJoinCode", reflect.TypeOf((*MockTransaction)(nil).GetTenantByJoinCode), ctx, code)
}

// GetTenantMembershipByTenantAndUser mocks base method.
func (m *MockTransaction) GetTenantMembershipByTenantAndUser(ctx context.Context, tenantID model.TenantID, userID model.UserID) (model.TenantMembership, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTenantMembershipByTenantAndUser", ctx, tenantID, userID)
	ret0, _ := ret[0].(model.TenantMembership)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTenantMembershipByTenantAndUser indicates an expected call of GetTenantMembershipByTenantAndUser.
func (mr *MockTransactionMockRecorder) GetTenantMembershipByTenantAndUser(ctx, tenantID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTenantMembershipByTenantAndUser", reflect.TypeOf((*MockTransaction)(nil).GetTenantMembershipByTenantAndUser), ctx, tenantID, userID)
}

// GetTenantsByUserID mocks base method.
func (m *MockTransaction) GetTenantsByUserID(ctx context.Context, userID model.UserID) ([]repository.TenantWithMemberCount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTenantsByUserID", ctx, userID)
	ret0, _ := ret[0].([]repository.TenantWithMemberCount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTenantsByUserID indicates an expected call of GetTenantsByUserID.
func (mr *MockTransactionMockRecorder) GetTenantsByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTenantsByUserID", reflect.TypeOf((*MockTransaction)(nil).GetTenantsByUserID), ctx, userID)
}

// GetUser mocks base method.
func (m *MockTransaction) GetUser(ctx context.Context, userID model.UserID) (model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", ctx, userID)
	ret0, _ := ret[0].(model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockTransactionMockRecorder) GetUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockTransaction)(nil).GetUser), ctx, userID)
}

// GetUserByProviderIdentity mocks base method.
func (m *MockTransaction) GetUserByProviderIdentity(ctx context.Context, provider, providerSub string) (model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByProviderIdentity", ctx, provider, providerSub)
	ret0, _ := ret[0].(model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByProviderIdentity indicates an expected call of GetUserByProviderIdentity.
func (mr *MockTransactionMockRecorder) GetUserByProviderIdentity(ctx, provider, providerSub any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByProviderIdentity", reflect.TypeOf((*MockTransaction)(nil).GetUserByProviderIdentity), ctx, provider, providerSub)
}

// IncrementJoinCodeUsedCount mocks base method.
func (m *MockTransaction) IncrementJoinCodeUsedCount(ctx context.Context, code model.TenantJoinCode) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementJoinCodeUsedCount", ctx, code)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrementJoinCodeUsedCount indicates an expected call of IncrementJoinCodeUsedCount.
func (mr *MockTransactionMockRecorder) IncrementJoinCodeUsedCount(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementJoinCodeUsedCount", reflect.TypeOf((*MockTransaction)(nil).IncrementJoinCodeUsedCount), ctx, code)
}

// RevokeAppSession mocks base method.
func (m *MockTransaction) RevokeAppSession(ctx context.Context, sessionID model.AppSessionID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeAppSession", ctx, sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeAppSession indicates an expected call of RevokeAppSession.
func (mr *MockTransactionMockRecorder) RevokeAppSession(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeAppSession", reflect.TypeOf((*MockTransaction)(nil).RevokeAppSession), ctx, sessionID)
}

// SaveOAuthState mocks base method.
func (m *MockTransaction) SaveOAuthState(ctx context.Context, oauthState model.OAuthState) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveOAuthState", ctx, oauthState)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveOAuthState indicates an expected call of SaveOAuthState.
func (mr *MockTransactionMockRecorder) SaveOAuthState(ctx, oauthState any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveOAuthState", reflect.TypeOf((*MockTransaction)(nil).SaveOAuthState), ctx, oauthState)
}

// UpdateTenant mocks base method.
func (m *MockTransaction) UpdateTenant(ctx context.Context, arg repository.UpdateTenantArg) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTenant", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTenant indicates an expected call of UpdateTenant.
func (mr *MockTransactionMockRecorder) UpdateTenant(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTenant", reflect.TypeOf((*MockTransaction)(nil).UpdateTenant), ctx, arg)
}

// UpdateTenantJoinCodeByTenantId mocks base method.
func (m *MockTransaction) UpdateTenantJoinCodeByTenantId(ctx context.Context, arg repository.UpdateTenantJoinCodeArg) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTenantJoinCodeByTenantId", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTenantJoinCodeByTenantId indicates an expected call of UpdateTenantJoinCodeByTenantId.
func (mr *MockTransactionMockRecorder) UpdateTenantJoinCodeByTenantId(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTenantJoinCodeByTenantId", reflect.TypeOf((*MockTransaction)(nil).UpdateTenantJoinCodeByTenantId), ctx, arg)
}

// UpsertUser mocks base method.
func (m *MockTransaction) UpsertUser(ctx context.Context, arg repository.UpsertUserArg) (model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertUser", ctx, arg)
	ret0, _ := ret[0].(model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertUser indicates an expected call of UpsertUser.
func (mr *MockTransactionMockRecorder) UpsertUser(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertUser", reflect.TypeOf((*MockTransaction)(nil).UpsertUser), ctx, arg)
}

// UpsertUserIdentity mocks base method.
func (m *MockTransaction) UpsertUserIdentity(ctx context.Context, arg repository.UpsertUserIdentityArg) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertUserIdentity", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertUserIdentity indicates an expected call of UpsertUserIdentity.
func (mr *MockTransactionMockRecorder) UpsertUserIdentity(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertUserIdentity", reflect.TypeOf((*MockTransaction)(nil).UpsertUserIdentity), ctx, arg)
}
