// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go
//
// Generated by this command:
//
//	mockgen -source=interface.go -destination=../mock/mock_usecase.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	model "github.com/shibayama-club/keyhub/internal/domain/model"
	dto "github.com/shibayama-club/keyhub/internal/usecase/console/dto"
	gomock "go.uber.org/mock/gomock"
)

// MockIUseCase is a mock of IUseCase interface.
type MockIUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockIUseCaseMockRecorder
	isgomock struct{}
}

// MockIUseCaseMockRecorder is the mock recorder for MockIUseCase.
type MockIUseCaseMockRecorder struct {
	mock *MockIUseCase
}

// NewMockIUseCase creates a new mock instance.
func NewMockIUseCase(ctrl *gomock.Controller) *MockIUseCase {
	mock := &MockIUseCase{ctrl: ctrl}
	mock.recorder = &MockIUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIUseCase) EXPECT() *MockIUseCaseMockRecorder {
	return m.recorder
}

// AssignRoomToTenant mocks base method.
func (m *MockIUseCase) AssignRoomToTenant(ctx context.Context, input dto.AssignRoomToTenantInput) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignRoomToTenant", ctx, input)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AssignRoomToTenant indicates an expected call of AssignRoomToTenant.
func (mr *MockIUseCaseMockRecorder) AssignRoomToTenant(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignRoomToTenant", reflect.TypeOf((*MockIUseCase)(nil).AssignRoomToTenant), ctx, input)
}

// CreateKey mocks base method.
func (m *MockIUseCase) CreateKey(ctx context.Context, input dto.CreateKeyInput) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateKey", ctx, input)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateKey indicates an expected call of CreateKey.
func (mr *MockIUseCaseMockRecorder) CreateKey(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateKey", reflect.TypeOf((*MockIUseCase)(nil).CreateKey), ctx, input)
}

// CreateRoom mocks base method.
func (m *MockIUseCase) CreateRoom(ctx context.Context, input dto.CreateRoomInput) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRoom", ctx, input)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRoom indicates an expected call of CreateRoom.
func (mr *MockIUseCaseMockRecorder) CreateRoom(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRoom", reflect.TypeOf((*MockIUseCase)(nil).CreateRoom), ctx, input)
}

// CreateTenant mocks base method.
func (m *MockIUseCase) CreateTenant(ctx context.Context, input dto.CreateTenantInput) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTenant", ctx, input)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTenant indicates an expected call of CreateTenant.
func (mr *MockIUseCaseMockRecorder) CreateTenant(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTenant", reflect.TypeOf((*MockIUseCase)(nil).CreateTenant), ctx, input)
}

// DeleteTenantById mocks base method.
func (m *MockIUseCase) DeleteTenantById(ctx context.Context, tenantId model.TenantID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTenantById", ctx, tenantId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTenantById indicates an expected call of DeleteTenantById.
func (mr *MockIUseCaseMockRecorder) DeleteTenantById(ctx, tenantId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTenantById", reflect.TypeOf((*MockIUseCase)(nil).DeleteTenantById), ctx, tenantId)
}

// GetAllRooms mocks base method.
func (m *MockIUseCase) GetAllRooms(ctx context.Context) ([]model.Room, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllRooms", ctx)
	ret0, _ := ret[0].([]model.Room)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllRooms indicates an expected call of GetAllRooms.
func (mr *MockIUseCaseMockRecorder) GetAllRooms(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllRooms", reflect.TypeOf((*MockIUseCase)(nil).GetAllRooms), ctx)
}

// GetAllTenants mocks base method.
func (m *MockIUseCase) GetAllTenants(ctx context.Context) ([]model.Tenant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllTenants", ctx)
	ret0, _ := ret[0].([]model.Tenant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllTenants indicates an expected call of GetAllTenants.
func (mr *MockIUseCaseMockRecorder) GetAllTenants(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllTenants", reflect.TypeOf((*MockIUseCase)(nil).GetAllTenants), ctx)
}

// GetKeysByRoom mocks base method.
func (m *MockIUseCase) GetKeysByRoom(ctx context.Context, roomID model.RoomID) ([]model.Key, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKeysByRoom", ctx, roomID)
	ret0, _ := ret[0].([]model.Key)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetKeysByRoom indicates an expected call of GetKeysByRoom.
func (mr *MockIUseCaseMockRecorder) GetKeysByRoom(ctx, roomID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKeysByRoom", reflect.TypeOf((*MockIUseCase)(nil).GetKeysByRoom), ctx, roomID)
}

// GetTenantById mocks base method.
func (m *MockIUseCase) GetTenantById(ctx context.Context, tenantId model.TenantID) (dto.GetTenantByIdOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTenantById", ctx, tenantId)
	ret0, _ := ret[0].(dto.GetTenantByIdOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTenantById indicates an expected call of GetTenantById.
func (mr *MockIUseCaseMockRecorder) GetTenantById(ctx, tenantId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTenantById", reflect.TypeOf((*MockIUseCase)(nil).GetTenantById), ctx, tenantId)
}

// LoginWithOrgId mocks base method.
func (m *MockIUseCase) LoginWithOrgId(ctx context.Context, orgID, orgKey string) (string, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoginWithOrgId", ctx, orgID, orgKey)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// LoginWithOrgId indicates an expected call of LoginWithOrgId.
func (mr *MockIUseCaseMockRecorder) LoginWithOrgId(ctx, orgID, orgKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoginWithOrgId", reflect.TypeOf((*MockIUseCase)(nil).LoginWithOrgId), ctx, orgID, orgKey)
}

// Logout mocks base method.
func (m *MockIUseCase) Logout(ctx context.Context, sessionID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logout", ctx, sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Logout indicates an expected call of Logout.
func (mr *MockIUseCaseMockRecorder) Logout(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logout", reflect.TypeOf((*MockIUseCase)(nil).Logout), ctx, sessionID)
}

// UpdateTenant mocks base method.
func (m *MockIUseCase) UpdateTenant(ctx context.Context, input dto.UpdateTenantInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTenant", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTenant indicates an expected call of UpdateTenant.
func (mr *MockIUseCaseMockRecorder) UpdateTenant(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTenant", reflect.TypeOf((*MockIUseCase)(nil).UpdateTenant), ctx, input)
}

// ValidateSession mocks base method.
func (m *MockIUseCase) ValidateSession(ctx context.Context, token string) (model.ConsoleSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateSession", ctx, token)
	ret0, _ := ret[0].(model.ConsoleSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateSession indicates an expected call of ValidateSession.
func (mr *MockIUseCaseMockRecorder) ValidateSession(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateSession", reflect.TypeOf((*MockIUseCase)(nil).ValidateSession), ctx, token)
}
